// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//import "dotenv/config";
//import { defineConfig } from "prisma/config";
//const { PrismaClient } = require("@prisma/client");
const { defineConfig } = require("prisma/config");
const dotenv = require("dotenv");
dotenv.config();


module.exports = defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});